<a href="https://colab.research.google.com/gist/YeisonAndresDiazPerdomo/6d75ad987e40f47d0642ca61a367b578/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [3]:
import numpy as np
arr =np.array([7,8,4,5,1,2])
arr


array([7, 8, 4, 5, 1, 2])

Using slicing print the elements from index 3 to the end of the array.



In [4]:
print(arr[2:])

[4 5 1 2]


Using slicing print all the elements except the last one.



In [5]:
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [6]:
print(arr[0:4])

[7 8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [8]:
rarr=arr.reshape(3,2)
rarr

array([[7, 8],
       [4, 5],
       [1, 2]])

Print all the array elements one by one (iterating).



In [14]:
for x in np.nditer(rarr):
  print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].

*   List item
*   List item





In [15]:
newarr=np.array([0,6,9])
newarr

array([0, 6, 9])

Join the two arrays.



In [17]:
joinarr=np.concatenate((arr,newarr))
joinarr

array([7, 8, 4, 5, 1, 2, 0, 6, 9])

Using filtering print only the odd numbers of the joined array.



In [20]:
filter_arr = []

for element in joinarr:
  if element ==0:
    filter_arr.append(False)
  elif element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
nuevoarr=joinarr[filter_arr]
print(nuevoarr)

[8 4 2 6]


Sort the joined array elements.



In [21]:
print(np.sort(joinarr))


[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [22]:
meses=np.array(['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembrte','octubre','noviembre','diciembre'])
meses

array(['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio',
       'agosto', 'septiembrte', 'octubre', 'noviembre', 'diciembre'],
      dtype='<U11')

Split the months array in 4 periods of 3 elements each one.



In [23]:
newmeses=np.array_split(meses,4)
newmeses

[array(['enero', 'febrero', 'marzo'], dtype='<U11'),
 array(['abril', 'mayo', 'junio'], dtype='<U11'),
 array(['julio', 'agosto', 'septiembrte'], dtype='<U11'),
 array(['octubre', 'noviembre', 'diciembre'], dtype='<U11')]

Create an array with genre information ['F','M','F','F','M','F'].



In [24]:
 genre=np.array(['F','M','F','F','M','F'])
 genre

array(['F', 'M', 'F', 'F', 'M', 'F'], dtype='<U1')

Find the indexes where the value is F.



In [26]:
xgenre=np.where(genre=='F')
xgenre

(array([0, 2, 3, 5]),)

Store in an array the age information [18,20,19,23,19,20].



In [27]:
age=np.array([18,20,19,23,19,20])
age

array([18, 20, 19, 23, 19, 20])

Create a filter array with values < 20.



In [28]:
filter_age = []

for element in age:
  if element <20:
    filter_age.append(True)
  else:
    filter_age.append(False)
newage=age[filter_age]
print(newage)

[18 19 19]


Change the 3 index element with a value of 22



In [29]:
age[2]=22
age

array([18, 20, 22, 23, 19, 20])

Print the 4 index element.

In [30]:
print(age[3])

23
